# Generated by Django 5.2.4 on 2025-09-17 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('anteprescolar', 'Antepreșcolar'), ('prescolar', 'Preșcolar'), ('primar', 'Primar'), ('gimnazial', 'Gimnazial'), ('liceal', 'Liceal')], max_length=20)),
                ('clasa', models.PositiveIntegerField()),
                ('litera', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'ordering': ['nivel', 'clasa', 'litera'],
                'unique_together': {('nivel', 'clasa', 'litera')},
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('nivel', models.CharField(choices=[('anteprescolar', 'Antepreșcolar'), ('prescolar', 'Preșcolar'), ('primar', 'Primar'), ('gimnazial', 'Gimnazial'), ('liceal', 'Liceal')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'nivel')},
            },
        ),
        migrations.CreateModel(
            name='PlanRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('anteprescolar', 'Antepreșcolar'), ('prescolar', 'Preșcolar'), ('primar', 'Primar'), ('gimnazial', 'Gimnazial'), ('liceal', 'Liceal')], max_length=20)),
                ('profil', models.CharField(blank=True, max_length=120, null=True)),
                ('clasa', models.PositiveIntegerField()),
                ('ore', models.PositiveIntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.area')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.subject')),
            ],
            options={
                'ordering': ['area__order', 'subject__name'],
                'unique_together': {('nivel', 'profil', 'clasa', 'area', 'subject')},
            },
        ),
    ]
