# Generated by Django 5.2.4 on 2025-09-17 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_schoolclass_teacher_planrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('educator', 'Educator'), ('diriginte', 'Diriginte')], max_length=20)),
                ('school_class', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assignment', to='school.schoolclass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_assignments', to='school.teacher')),
            ],
            options={
                'ordering': ['school_class__nivel', 'school_class__clasa', 'school_class__litera'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField()),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='school.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='school.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='school.teacher')),
            ],
            options={
                'ordering': ['school_class__nivel', 'school_class__clasa', 'subject__name'],
                'indexes': [models.Index(fields=['school_class', 'subject'], name='school_allo_school__a75e8e_idx'), models.Index(fields=['teacher'], name='school_allo_teacher_460f86_idx')],
                'unique_together': {('teacher', 'school_class', 'subject')},
            },
        ),
    ]
